#pragma once

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define TAPPING_TERM_PER_KEY

#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 500
#define COMBO_TERM 100
#define COMBO_TERM_PER_COMBO

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// disable shit
#define NO_MUSIC_MODE

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define RP2040_FLASH_GENERIC_03H

#define WS2812_DI_PIN GP0
#define WS2812_PIO_USE_PIO1

#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL